### ISSUE TITLE
再次定位出错：kotlin.TypeCastException: null cannot be cast to non-null type com.amap.api.location.AMapLocationClient

### ISSUE THREAD

**Issue by AiHMin** [fluttify-project/amap_location_fluttify#5]
**插件版本**
`amap_location_fluttify: ^0.2.5+ed34f18`

**描述bug**
在一个页面使用定位之后，关闭页面(页面mixin了`AmapLocationDisposeMixin`)，再次进入该界面，点击定位，报以下错误
```
E/MethodChannel#me.yohom/amap_location_fluttify(17942): Failed to handle method call
E/MethodChannel#me.yohom/amap_location_fluttify(17942): kotlin.TypeCastException: null cannot be cast to non-null type com.amap.api.location.AMapLocationClient
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at me.yohom.amap_location_fluttify.AmapLocationFluttifyPlugin$handlerMap$16.invoke(AmapLocationFluttifyPlugin.kt:372)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at me.yohom.amap_location_fluttify.AmapLocationFluttifyPlugin$handlerMap$16.invoke(AmapLocationFluttifyPlugin.kt:15)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at me.yohom.amap_location_fluttify.AmapLocationFluttifyPlugin.onMethodCall(AmapLocationFluttifyPlugin.kt:5323)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#me.yohom/amap_location_fluttify(17942): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (17942): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, null cannot be cast to non-null type com.amap.api.location.AMapLocationClient, null)
E/flutter (17942): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (17942): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (17942): <asynchronous suspension>
E/flutter (17942): #2      com_amap_api_location_AMapLocationClient.stopLocation (package:amap_location_fluttify/src/android/com/amap/api/location/AMapLocationClient.g.dart:102:75)
E/flutter (17942): <asynchronous suspension>
E/flutter (17942): #3      AmapLocation.stopLocation.<anonymous closure> (package:amap_location_fluttify/src/dart/amap_location.dart:127:41)
E/flutter (17942): #4      platform (package:foundation_fluttify/src/function/functions.dart:52:33)
E/flutter (17942): <asynchronous suspension>
E/flutter (17942): #5      AmapLocation.stopLocation (package:amap_location_fluttify/src/dart/amap_location.dart:126:12)
E/flutter (17942): #6      _DormitoryCheckPageState.stopLocation (package:smart_qfnu/pages/daily/check_in/dormitory_page.dart:375:18)
E/flutter (17942): #7      _DormitoryCheckPageState._requestCheck (package:smart_qfnu/pages/daily/check_in/dormitory_page.dart:302:5)
E/flutter (17942): <asynchronous suspension>
E/flutter (17942): #8      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
E/flutter (17942): #9      _rootRun (dart:async/zone.dart:1120:38)
E/flutter (17942): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (17942): #11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (17942): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (17942): #13     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (17942): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (17942): #15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (17942): #16     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (17942): #17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (17942): #18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (17942): #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**复现步骤**
在一个页面（页面mixin了`AmapLocationDisposeMixin`）使用定位之后，pop掉页面后，再次进入该界面，点击定位，报错

已尝试`flutter pub upgrade`和将插件完全删除重新`flutter pub get`

**期望行为**

正常定位

**截图**
![image](https://user-images.githubusercontent.com/28809242/67833260-21bb6d00-fb1f-11e9-84b0-1331d1dcca28.png)

**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.15 19A602, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] Android Studio
[!] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.39.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by yohom** [comment]
临时的解决方案是在全局级别的State中释放，具体细节我再看下。@AiHMin

**Comment by AiHMin** [comment]
好的👌谢谢啦 @yohom

**Comment by yohom** [comment]
@AiHMin `0.2.6`版本已处理这个问题。
